go_setup: &go_setup
  docker:
  - image: circleci/golang:1.12.5

go_mod_download: &go_mod_download
  run:
    name: Download Go modules
    command: go mod download

version: 2.1
jobs:
  build:
    <<: *go_setup
    steps:
    - checkout
    - *go_mod_download
    - run:
        name: Build all targets
        command: go build -v ./...
  test:
    <<: *go_setup
    steps:
    - checkout
    - *go_mod_download
    - run:
        name: Run all tests
        command: go test -v ./...
workflows:
  build_and_test:
    jobs:
    - build
    - test:
        requires:
        - build
